#!/bin/bash
function tex2pdf {

    local l=${#1}
#    echo $l
    for f in $1$2; do
	local fs=${f:$l}
	echo $f
# $fs
        pdflatex $f.tex
    done
}

cp doxygen-common.cfg doxygen_tmp.cfg
cat doxygen-en.cfg >>doxygen_tmp.cfg
doxygen doxygen_tmp.cfg

cp doxygen-common.cfg doxygen_tmp.cfg
cat doxygen-ru.cfg >>doxygen_tmp.cfg
doxygen doxygen_tmp.cfg

#tex2pdf ananas-script-ru

rm doxygen_tmp.cfg
